baseURL = 'https://sanjean.com/'
languageCode = 'en-us'
title = "San Jean's Thoughts"
theme = "hugo-PaperMod"

[params]
mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "themes"
    name = "Themes"
    url = "/themes/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
